//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;
	using System.Data.Entity.Core.Objects;
	using System.Linq;
	using Utility;

	public partial class UIDBEntities : DbContext
    {
        public UIDBEntities()
            : base("name=UIDBEntities")
        {
		}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPermission> UserPermission { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<TaskList> TaskList { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<DocumentFolder> DocumentFolder { get; set; }
        public virtual DbSet<DocumentTag> DocumentTag { get; set; }
    
        public virtual ObjectResult<GetFolderInfo_Result> GetFolderInfo(Nullable<System.DateTime> createDate)
        {
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("createDate", createDate) :
                new ObjectParameter("createDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFolderInfo_Result>("GetFolderInfo", createDateParameter);
        }
    
        public virtual ObjectResult<GetUnfinishTaskPer_Result> GetUnfinishTaskPer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUnfinishTaskPer_Result>("GetUnfinishTaskPer");
        }
    }
}
